version: "3"

services:
  react-router-app:
    build:
      context: ./react-router
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/local_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.react-router-app.rule=Host(`react-router-app.dokploy.com`)
      - traefik.http.routers.react-router-app.entrypoints=websecure
      - traefik.http.routers.react-router-app.tls.certResolver=letsencrypt
      - traefik.http.services.react-router-app.loadbalancer.server.port=3000

  db:
    image: postgres:16.4
    restart: always
    container_name: base-stack-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: local_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dokploy-network

volumes:
  postgres_data:

networks:
  dokploy-network:
    external: true
